{% set name = "smart_open" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/piskvorky/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 20b20c92fe538d957f05bba99477ababb64e9ceb47c7d48ea30184c0d0aefef4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python
    - wrapt
  run_constrained:
    # gcs
    - google-cloud-storage >=2.6.0

# E   ModuleNotFoundError: No module named 'google'
{% set ignore_tests = "--ignore=tests/test_gcs.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_smart_open.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_compression.py" %} # [py<314]

test:
  source_files:
    - tests
  imports:
    - smart_open
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }}
  requires:
    - pip
    - pytest
    - pytest-rerunfailures
    - responses
    - azure-storage-blob
    - azure-common
    - azure-core
    - paramiko
    - boto3
    - zstandard
    - moto

about:
  home: https://github.com/RaRe-Technologies/smart_open
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utils for streaming large files (S3, HDFS, GCS, SFTP, Azure Blob Storage, gzip, bz2, zst...)
  description: |
    smart_open is a Python 3 library for efficient streaming of very large
    files from/to storages such as S3, GCS, Azure Blob Storage, HDFS, WebHDFS,
    HTTP, HTTPS, SFTP, or local filesystem.  It supports transparent,
    on-the-fly (de-)compression for a variety of different formats
  dev_url: https://github.com/RaRe-Technologies/smart_open
  doc_url: https://github.com/RaRe-Technologies/smart_open/blob/develop/README.rst

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
  skip-lints:  # [win]
    - missing_pip_check  # [win]
    - missing_tests  # [win]
    - missing_imports_or_run_test_py  # [win]
