travis:
  secure:
    BINSTAR_TOKEN: FCLjcbIiQ1MB8BsqWYzjBKqpBVRC6jI7Vn4pM5uiL5/Gv5rfjQe3QWFl7uuYNmbJO7jtTvXVY8S/9sh/OtPBUWo1yirPd+OyM69c22bTBWuKWme+hEZWiXA70Wf4ffNfUkQaURYylg0xus0b8/ztroPpA5JFSaBdDVLx3jdCaShld7z+m12FpI4D7hT7rmpCZ3rnBYqIKe7mTa3AWuPcT7WK6814ZaAzHf0hGIkj0XSVI9psYGPb1q6yZ2O8ut6ssW0r9JPhwRrN3ULBuZr04RHLPWU1t3v/8DFA/f3sfqw38MjVWCtauWmXt2PixeaGNuT3LmFem5lCf5sXoHxkPZcDaP5/6Fhj01SspPfgqNHJefL/0Mq1CZrlHfxVZg4HPdtg1ID5nLtlEaF0F1WXl4lBSAWVaHF7tgYD9De94Q0tAGrsJ7ZNgBeUl3pkNryeGljao7WBeumdevQKgLAQimd2u8wtiE/F+/JyAikAzVtXi+UeqYdaL/lP/ec9ff5dZfA8YdCg6NYiejKCYAtsryf6hkW2Tf2J+xmf1D5bdvSTRAPEgaXgRYbpURorpX/l9JGQbMnlop/e+2pHjtmpR+Hpxa2BC7ayaILiGpR9sZNdT3JdBlDoq6lm5RGi/UDraubc01xMdpp7vk6jFhdvIvhysOPuUKsD+Lib3b/gJtI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
