travis:
  secure:
    BINSTAR_TOKEN: TPh+Q+pdvWpWPtq9dY/fjzg3lOdWV2qh0M0viuNdJM9uN9ofCM9j0l5svR0YbcT+ter4zLDKH9u7hpNe7vA+nq80edpGcRL4+noyDkVYA+YU1/1ptwswWxBTkWOISyMsLAbNlzaZ3HpHYUEBPc+vAyaTJZ95wgTT2NOlgfbUkeYCV2bmTWyqnDXubY0Y/ZE67ghujH0p0SD7bS7Ia/dnrWKMNHniXAIwJ0oBklWoaeUPCwR7DCNs2XwWV+etFfOf7toldR9EN7juKqZucTtuD3U12AB5bp/v7zG+7svex96z0ENcXJ+sPmC+YP3KbhsY00OOS28uZh4sECa2LI7gVdirk6KVi6fzTyeTHRUMmsYHtdfV2pLJsNHLPedLw4lvANuM+nDQ+NC0A0KtcaTkmel8+feMoVWgGX/XVmtyXtYI1Gp5OIUxyqw/xARdKG6GuYxCdGx3F+PG+hEM2L5fAwzXeAN7R1juMhRC6sgciqi5vrmlYhze3Rz8iHIVLJow+Bvh5hiwWhv542lX5y8MVPu6UmCq2daRf614TUu9yitpJ0Ngrkw9QY4tyMXlxQkkL/+EeGcCgmIKtx6pzcXywV1GMvntyGqnYVQ+rFcfphOhTyXXl20FS+FajHV5bx5hKgT3Fvb0rRiI6U+PYPyf6KThoZ+hC03i4sKKL/kiTys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
