travis:
  secure:
    BINSTAR_TOKEN: uguUATZ0uxGsdpqAu3SIjccciFrCtLXckq1jHWIn6MfCD+pUGfBryonhlkySI27UAybSbyXT0G7ecmVv0ykPcrXISIIZw0cnfswcCRRc9nnLWZ++NIcQc4z0IyDznQv9K/aC8/mVw8g8FxzVCwaoKvf2FNXAmsM8HwtryB5UXFeFdOzdG9AjkB98rWSWNQ1pSrORsTwVH8nO88iILFJbBlD3MusPFlzssn2eA3VcXnjDMHaLkUsn6N0GMuIiFBQ9CIJgYCqNg+Ll7EQGSNHgWXkW5jtVK67HJkJbUlSdt5/FJF7XndibFREV4MmSc5nb0P9oPtH9ZzvrnFvytLOOTS0eQUls9Qi1UfP/2aE4qOOLfIc9nHxAIEPLSqT89vnOcDFA5zKGY0GjNAqsP8959XUj5qwjXJ5NHlRBARP1itZNURmxUPtNOL4AekWDWPsNCNXQTslY7tRvoziY1ZnH21sdc5yqahglYpaPY3dWnET0zEL78EtjAmPPqHSips7bQzqYttzmdrdC+vq6SLDMRzC+RterVvZ7lkChBZNnzI8kd04mQpPMblAfr5WP9nu/RsWwafbfgq0hPPDRX5BIfH3KejdsDaW4mnA8WbmerXCxPSX+HdHHr0b8OcAyqjF6S62YCqFTeBCOPONPcoFYDs2Zk4SvFOAW/gskWK0XJWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
